# Class 4: Numpy

## 1. Numpy arrays

fl_sp holds the floor spaces in square meters of 5 stores.
turnover holds the turnover in GBP of 5 stores

- Import Numpy
- Convert the lists into Numpy arrays
- Print the types of the arrays
- Turnover is in GBP, convert the turnover array into an new array that shows turnover in EUR. Find the the current exchange rate on the Internet. Print the new array.
- Calculate the EUR turnover per square meter (sqm) per store in a new array. Print the first three items of the new array.
- A turnover per sqm of higher than 230 is considered to be good. Print the elements that are higher than this threshold.
- Print the highest turnover

In [2]:
fl_sp = [18526, 18569, 12288, 17092, 11307]
turnover = [3410865, 4034051,2297810, 2398990, 2288235]

#Import:
import numpy as np

#Convert to arrays
fl_sp_arr = np.array(fl_sp)

# (oscar) casting it to a float so that we can multiply the values within the array later on in the following exercise
turnover_arr = np.array(turnover).astype(float)

#Print types
print(type(fl_sp_arr))
print(type(turnover_arr))

#Convert to EUR and print
turnover_arr *= 1.18

print(turnover_arr)

#Calculate EUR turnover per sqm and print first 3 items
for index in range(3):
    print(turnover_arr[index] / fl_sp_arr[index])

#Print to per sqm > 230
for index in range(turnover_arr.size):
    if turnover_arr[index] // fl_sp_arr[index] < 230:
        continue

    print(f'turnover {turnover_arr[index]}')
    print(f'fl_sp {fl_sp_arr[index]}')

#Print the highest turnover
highest = turnover_arr[0]

for to in turnover_arr:
    if to <= highest:
        continue

    highest = to

print(highest)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[4024820.7  4760180.18 2711415.8  2830808.2  2700117.3 ]
217.25254777070063
256.35091711993107
220.65558268229165
turnover 4760180.18
fl_sp 18569
turnover 2700117.3
fl_sp 11307
4760180.18


## 2 Numpy 2D arrays
The list of lists fl_sp_to contains the floorspaces (sqm) and turnovers in GBP of 5 stores.
- Convert the list of lists into an 2D array
- Print the shape of the array
- Print the second column of the last 4 rows
- Print the second row up to and including the 4th row
- Convert the floor spaces into feet and convert the GBP amounts in EUR. Look up the appropriate conversion factors on the Internet. Print the new array.
- Each store manager gets a bonus. The bonus percentages are given in the bonus table which is a list of lists. Print a new array that shows the bonus amounts.

In [8]:
fl_sp_to = [[18526, 3410865],
            [18569, 4034051],
            [12288, 2297810], 
            [17092, 2398990], 
            [11307, 2288235]]

#Convert into a 2D array
fl_sp_to_arr = np.array(fl_sp_to)

#print shape
print(fl_sp_to_arr.shape)

#print second column of last 4 rows
for idx, fl_sp_to_couple in enumerate(reversed(fl_sp_to_arr)):
    if idx > 3:
        break

    print(fl_sp_to_couple[1])

#print second row up to and including the 4th row
for idx, fl_sp_to_couple in enumerate(fl_sp_to_arr):
    if idx >= 3:
        break

    print(fl_sp_to_couple[1])

#Convert to square feet and EUR
for idx, fl_sp_to_couple in enumerate(fl_sp_to_arr):
    fl_sp_to_arr[idx][0] = float(fl_sp_to_couple[0]) * 10.76391
    fl_sp_to_arr[idx][1] = float(fl_sp_to_couple[1]) * 1.18

print(fl_sp_to_arr)


#Bonus table
bonus = [[1, 0.010],
         [1, 0.008],
         [1, 0.007], 
         [1, 0.011], 
         [1, 0.005]]

# bonus amount
bonus_arr = np.array(bonus).astype(float)
bonus_calculated = list()

for idx, bonus_couple in enumerate(bonus_arr):
    bonus_calculated.append(bonus_couple[0] * bonus_couple[1])

bonus_calculated = np.array(bonus_calculated)

print(bonus_calculated)


(5, 2)
2288235
2398990
2297810
4034051
3410865
4034051
2297810
[[ 199412 4024820]
 [ 199875 4760180]
 [ 132266 2711415]
 [ 183976 2830808]
 [ 121707 2700117]]
[0.01  0.008 0.007 0.011 0.005]


## 3 Integration assignment

In the next cell we'll read some real store data into this notebook from a CSV file using Pandas. This is something that you'll learn in one of your next classes. As a result there is 2D numpy array st_to available for you to use in this assignment. 

It shows the number of staff members and the turnover per store. We expect that there might be a correlation between the number of staff members and the turnover.
- Calculate the mean, median and standard deviation of both columns
- What is your first impression of the data in the staff column? What about the turnover?
- Check the data, are there any strange data points? which?
- Print the correlation coefficient of both columns
- What options do you have to get a more accurate result?


In [21]:
# Don't remove this:
import pandas as pd
import numpy as np

storedata = pd.read_csv('storedata.csv', encoding='ISO-8859-1')
staff = storedata['Staff'].values.tolist()
turnover = storedata['Profit'].values.tolist()

np_st = np.array(staff)
np_to = np.array(turnover)
st_to = np.column_stack((np_st,np_to))

# Start coding here:
mean_staff = np.mean(st_to[0])
median_staff = np.median(st_to[0])
standard_deviation_staff = np.std(st_to[0])

mean_to_p_s = np.mean(st_to[1])
median_to_p_s = np.median(st_to[1])
standard_deviation_to_p_s = np.std(st_to[1])

print(f'staff - mean: {mean_staff}, median: {median_staff}, standard deviation: {standard_deviation_staff}')
print(f'turnover per store - mean: {mean_to_p_s}, median: {median_to_p_s}, standard deviation: {standard_deviation_to_p_s}\n')

print(f'correlation coefficient: {np.corrcoef(st_to)}')

staff - mean: 1705437.0, median: 1705437.0, standard deviation: 1705428.0
turnover per store - mean: 2017029.5, median: 2017029.5, standard deviation: 2017021.5

correlation coefficient: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
